### ISSUE TITLE
How to ptch telegram with your sources ?

### ISSUE THREAD

**Issue by Adity1243** [Aunali321/ReVancedExperiments#11]
### Bug description

.

### Error logs

```shell
.
```

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Aunali321** [comment]
![Screenshot_20241112_034452_ReVanced Manager](https://github.com/user-attachments/assets/fe20ed1a-1fd3-4f3d-8b3b-bfd57508f16d)
